%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3202}
\newcommand{\className}{Introduction To Artifical Intelligence}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignments/}
\newcommand{\ExamNotesDir}{./Exam Notes/}
\newcommand{\ExamsDir}{./Exams/}
\newcommand{\LecNoteDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\ReadMatDir}{./Reading Material/}
\newcommand{\AITextbook}{\pdflink{./Textbook/Artificial Intelligence - A Modern Approach (Fourth Edition) - Stuart Russel, Peter Norvig.pdf}{Artificial Intelligence - A Modern Approach}}
\newcommand{\RLTextbook}{\pdflink{./Textbook/Reinforcement Learning - An Introduction (Second Edition) - Richard Sutton, Andrew Barto.pdf}{Reinforcement Learning - An Introduction}}