%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Student Name}
\newcommand{\classCode}{Course Code}
\newcommand{\className}{Course Name}
\newcommand{\documentName}{Assignment Name}
\newcommand{\universityName}{University Of Colorado}