%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3702}
\newcommand{\className}{Cognitive Science}
\newcommand{\documentName}{Mini Project 1 - Digital Automata}
\newcommand{\universityName}{University Of Colorado}