%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 4622}
\newcommand{\className}{Machine Learning}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignment/}
\newcommand{\LecNoteDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\TextbookDir}{./Textbook/}
\newcommand{\ISLRPython}{\pdflink{\TextbookDir An Introduction To Statistical Learning With Applications In Python (First Edition) - Gareth James.pdf}{An Introduction To Statistical Learning With Applications In Python}}
\newcommand{\ISLRR}{\pdflink{\TextbookDir An Introduction To Statistical Learning With Applications In R (First Edition) - Gareth James.pdf}{An Introduction To Statistical Learning With Applications In R}}
\newcommand{\ESLII}{\pdflink{\TextbookDir The Elements Of Statistical Learning Data Mining, Inference, And Prediction (Second Edition) - Trevor Hastie, Robert Tibshirani, Jerome Friedman.pdf}{The Elements Of Statistical Learning Data Mining, Inference, And Prediction}}