%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3022}
\newcommand{\className}{Introduction To Data Science With Probability And Statistics}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignments/}
\newcommand{\ExamDir}{./Exams/}
\newcommand{\ExamNotesDir}{./Exam Notes/}
\newcommand{\LecNoteDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\LearnDSBook}{\pdflink{./Textbook/Learning Data Science Data Wrangling, Exploration, Visualization, and Modeling with Python (First Edition) - Sam Lau, Joseph Gonzalez, Deborah Nolanpdf.pdf}{Learning Data Science Data Wrangling, Exploration, Visualization, and Modeling with Python}}
\newcommand{\PyDSBook}{\pdflink{./Textbook/Python for Data Analysis Data Wrangling with pandas, NumPy, and Jupyter (Third Edition) - Wes McKinney.pdf}{Python for Data Analysis Data Wrangling with pandas, NumPy, and Jupyter}}