%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3202}
\newcommand{\className}{Introduction To Artifical Intelligence}
\newcommand{\documentName}{Exam Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------