%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3022}
\newcommand{\className}{Introduction To Data Science With Probability And Statistics}
\newcommand{\documentName}{Exam Notes}
\newcommand{\universityName}{University Of Colorado}