%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3308}
\newcommand{\className}{Software Devlopment Methods And Tools}
\newcommand{\documentName}{Exam Notes}
\newcommand{\universityName}{University Of Colorado}