%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 2824}
\newcommand{\className}{Discrete Structures}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}