%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3155}
\newcommand{\className}{Principles Of Programming Languages}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignments/}
\newcommand{\ExamNotesDir}{./Exam Notes/}
\newcommand{\ExamsDir}{./Exams/}
\newcommand{\LecNoteDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\ReadMatDir}{./Reading Material/}
\newcommand{\AtomicScalaBook}{\pdflink{./Textbook/Atomic Scala - Learn Programming In The Language Of The Future (Second Edition) - Dianne Marsh, Bruce Eckel.pdf}{Atomic Scala - Learn Programming In The Language Of The Future}}
\newcommand{\EssOfPPLBook}{\pdflink{./Textbook/Essentials Of Programming Languages (Third Edition) - Daniel P. Friedman, Mitchell Wand.pdf}{Essentials Of Programming Languages}}
\newcommand{\FuncOfPPLBook}{\pdflink{./Textbook/Functional Programming In Scala (First Edition) - Paul Chiusano, Runar Bjarnason.pdf}{Functional Programming In Scala}}
\newcommand{\ProgInScalaBook}{\pdflink{./Textbook/Programming In Scala (Third Edition) - Martin Odersky, Lex Spoon, Bill Venners.pdf}{Programming In Scala}}