%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3104}
\newcommand{\className}{Algorithms}
\newcommand{\documentName}{Exam Notes}
\newcommand{\universityName}{University Of Colorado}