%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 2270}
\newcommand{\className}{Data Structures}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\ExamNotesDir}{./Exam Notes/}
\newcommand{\ExamDir}{./Exams/}
\newcommand{\InterviewDir}{./Interview Notes/}
\newcommand{\LectureNotesDir}{./Lecture Notes/}
\newcommand{\ReadingMatDir}{./Reading Material/}