%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3104}
\newcommand{\className}{Algorithms}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignments/}
\newcommand{\ExamNotesDir}{./Exam Notes/}
\newcommand{\ExamsDir}{./Exams/}
\newcommand{\LecNoteDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\ReadMatDir}{./Reading Material/}
\newcommand{\Textbook}{\pdflink{./Textbook/Introduction to Algorithms (Third Edition) - Cormen, Thomas H. Leiserson, Charles E. Rivest, Ronald L. Stein.pdf}{Introduction to Algorithms}}