%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 2820}
\newcommand{\className}{Linear Algebra With Computer Science Applications}
\newcommand{\documentName}{Study Guide 8 - Linear Equations}
\newcommand{\universityName}{University Of Colorado}