%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Student Name}
\newcommand{\classCode}{Course Code}
\newcommand{\className}{Course Name}
\newcommand{\documentName}{Document Name}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignment/}
\newcommand{\LecNoteDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}