%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 2400}
\newcommand{\className}{Computer Systems}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignments/}
\newcommand{\ExamDir}{./Exams/}
\newcommand{\ExamNotesDir}{./Exam Notes/}
\newcommand{\LecNoteDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\ReadingMatDir}{./Reading Material/}
\newcommand{\Textbook}{\pdflink{./Textbook/Computer Systems A Programmer's Perspective (Third Edition) - Randal E. Bryant, David R. O'Hallaron.pdf}{Computer Systems A Programmer's Perspective (Third Edition)}}