%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3753}
\newcommand{\className}{Operating Systems}
\newcommand{\documentName}{Exam Notes}
\newcommand{\universityName}{University Of Colorado}