%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 2820}
\newcommand{\className}{Linear Algebra With Computer Science Applications}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignments/}
\newcommand{\ExamNotesDir}{./Exam Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\ReadMatDir}{./Reading Material/}
\newcommand{\VMLS}{\pdflink{./Textbook/Introduction To Applied Linear Algebra (1st Edition) - Stephen Boyd And Lieven Vandenberghe.pdf}{Introduction To Applied Linear Algebra, Vectors, Matrices, And Least Squares}}
\newcommand{\PyCap}{\pdflink{./Textbook/Introduction to Applied Linear Algebra, Vectors, Matrices, And Least Squares (1st Edition) - Jessica Leung And Dmytro Matsypura.pdf}{Introduction to Applied Linear Algebra, Vectors, Matrices, And Least Squares - Python Companion}}