%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3702}
\newcommand{\className}{Cognitive Science}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignments/}
\newcommand{\LectNotesDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\ReadingMatDir}{./Reading Material/}