%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 4622}
\newcommand{\className}{Machine Learning}
\newcommand{\documentName}{Programming Assignment 1}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignment/}
\newcommand{\LecNoteDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
%---------------------------------------------------------------------------
%	CUSTOM
%---------------------------------------------------------------------------
\newcommand{\subsec}[1]{
    \subsection*{#1}
    \addcontentsline{toc}{subsection}{#1}
}