%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3308}
\newcommand{\className}{Software Devlopment Methods And Tools}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\ExamNotesDir}{./Exam Notes/}
\newcommand{\ExamsDir}{./Exams/}
\newcommand{\LecNoteDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\ReadMatDir}{./Reading Material/}
\newcommand{\AgileBook}{\pdflink{./Textbook/Agile For Dummies (Limited Edition) - Scott Ambler, Matthew Holitza.pdf}{Agile For Dummies}}
\newcommand{\EngSoftBook}{\pdflink{./Textbook/Engineering Software As A Service - An Agile Approach Using Cloud Computing (First Edition) - Armando Fox, David Patterson.pdf}{Engineering Software As A Service - An Agile Approach Using Cloud Computing}}
\newcommand{\ProGitBook}{\pdflink{./Textbook/Pro Git (Second Edition) - Scott Chacon, Ben Straub.pdf}{Pro Git}}
\newcommand{\LinuxBook}{\pdflink{./Textbook/The Linux Command Line (Fifth Edition) - William Shotts.pdf}{The Linux Command Line}}