%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 2824}
\newcommand{\className}{Discrete Structures}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignments/}
\newcommand{\ExamsDir}{./Exams/}
\newcommand{\LectureNotesDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\ReadMatDir}{./Reading Material/}
\newcommand{\Textbook}{\pdflink{./Textbook/Discrete Mathematics And Its Applications (7th Edition) - Kenneth Rosen.pdf}{Discrete Mathematics And Its Applications}}