%---------------------------------------------------------------------------
%	DOCUMENT VARIABLES
%---------------------------------------------------------------------------
\input{Classes/GoldenCommands.cls}
\newcommand{\authorName}{Taylor Larrechea}
\newcommand{\classCode}{CSPB 3753}
\newcommand{\className}{Operating Systems}
\newcommand{\documentName}{Class Notes}
\newcommand{\universityName}{University Of Colorado}
%---------------------------------------------------------------------------
%	LOCAL DIRECTORIES
%---------------------------------------------------------------------------
\newcommand{\AssDir}{./Assignment/}
\newcommand{\ExamNoteDir}{./Exam Notes/}
\newcommand{\ExamsDir}{./Exams/}
\newcommand{\LecNoteDir}{./Lecture Notes/}
\newcommand{\QuizDir}{./Quizzes/}
\newcommand{\TextBookDir}{./Textbook/}